### ISSUE TITLE
Support .php-version.toml and argument configure-opts?

### ISSUE THREAD

**Issue by jmjoy** [masan4444/phpup#30]
Just a suggestion.

For example:

```toml
version = "8.1.0"
configure-opts = "--with-iconv=$(brew --prefix libiconv)"
```
